Quiz
* Explain why the distinction between the test error rate and the training error rate is important.
* What are the two problems of validation that cross-validation addresses?

Vocabulary
* Cross-Validation
* Bootstrap
* model assessment
* model selection
* validation set (approach)
* hold-out set
* cross-validation
* Leave-one-out-cross-validation (LOOCV)
* $k$-fold cross-validation ($k$-fold CV)

# Code

How to compute the k-fold validation split for an array `x`.

In [18]:
import numpy as np
_rng = np.random.default_rng()
x: np.ndarray[np.float32] = np.arange(100).astype(np.float32) + 1
_rng.shuffle(x)

k = 5
k_fold: list[np.ndarray] = np.array_split(x, k)
k_fold

[array([85., 35., 82., 36., 14.,  5., 27., 86., 79., 69., 45., 38., 20.,
        73., 40., 31., 84.,  1., 50., 41.], dtype=float32),
 array([81., 61., 37., 96., 98., 89., 66., 21., 64., 26., 19., 62., 16.,
        34.,  9., 55., 49., 68., 88., 22.], dtype=float32),
 array([47.,  8., 65.,  6., 29., 77., 93.,  4., 44., 12., 80., 99., 17.,
        94., 71.,  7., 67., 25., 58., 48.], dtype=float32),
 array([ 90.,  52.,  11.,  53.,  74.,  97.,  43.,  57.,  30.,  33.,  78.,
         72.,  39.,  18.,  76.,  51.,  60.,  91.,  87., 100.],
       dtype=float32),
 array([10., 92., 46., 56., 75., 42., 54., 24., 70., 13., 83., 23., 95.,
        32., 63., 15.,  3., 59., 28.,  2.], dtype=float32)]